# Generated by Django 3.0.8 on 2021-04-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0011_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='max_weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='min_weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='price',
            field=models.FloatField(),
        ),
    ]
