# Generated by Django 3.0.8 on 2021-04-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0012_auto_20210407_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=35)),
                ('address1', models.CharField(max_length=35)),
                ('address2', models.CharField(blank=True, max_length=35)),
                ('address3', models.CharField(blank=True, max_length=35)),
                ('city', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=35)),
                ('province', models.CharField(max_length=35)),
            ],
        ),
    ]
