# Generated by Django 3.0.8 on 2021-04-07 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0015_remove_shipping_details_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping_details',
            name='shipment_owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_shipment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shipping_details',
            name='shipping_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_reference', to='shoppingcart.Shipping'),
        ),
    ]
