# Generated by Django 3.0.8 on 2021-04-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0016_auto_20210407_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping_details',
            name='country',
            field=models.CharField(default='Philippines', max_length=35),
        ),
    ]
