# Generated by Django 3.0.8 on 2021-04-08 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0021_auto_20210407_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_owner', to=settings.AUTH_USER_MODEL)),
                ('shipping_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_details', to='shoppingcart.Shipping_Details')),
                ('shipping_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_shipment_type', to='shoppingcart.Shipping')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respective_order', to='shoppingcart.Job_Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_product', to='shoppingcart.Product')),
            ],
        ),
    ]
