# Generated by Django 3.0.8 on 2021-04-08 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0022_job_items_job_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_order',
            name='shipping_type',
        ),
    ]
