# Generated by Django 3.0.8 on 2021-02-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210223_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_maximum',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
