# Generated by Django 3.0.8 on 2021-02-23 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210220_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_link',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='listing',
            name='item_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.Category'),
        ),
    ]
