# Generated by Django 3.0.8 on 2021-05-10 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_bid_is_maximum'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='stream_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
