# Generated by Django 3.0.8 on 2021-05-31 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_listing_stream_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auctioned_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auctioned_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Listing')),
                ('new_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Bid')),
            ],
        ),
    ]
